import { ComparisonResult, SchemaChange, ChangeRiskLevel } from '../../shared/types';
import * as Diff from 'diff';

class ReportGeneratorService {
  /**
   * Generate an HTML report for schema comparison results
   */
  public generateHtmlReport(result: ComparisonResult): string {
    const stats = this.calculateStats(result.changes);
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Schema Comparison Report</title>
  <style>
    ${this.getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>Schema Comparison Report</h1>
      <div class="report-meta">
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Source:</strong> ${this.escapeHtml(result.source.name)}</p>
        <p><strong>Target:</strong> ${this.escapeHtml(result.target.name)}</p>
      </div>
    </header>

    <section class="summary">
      <h2>Summary</h2>
      <div class="stats-grid">
        <div class="stat-card stat-total">
          <div class="stat-number">${stats.total}</div>
          <div class="stat-label">Total Changes</div>
        </div>
        <div class="stat-card stat-safe">
          <div class="stat-number">${stats.safe}</div>
          <div class="stat-label">Safe</div>
        </div>
        <div class="stat-card stat-warning">
          <div class="stat-number">${stats.warning}</div>
          <div class="stat-label">Warning</div>
        </div>
        <div class="stat-card stat-destructive">
          <div class="stat-number">${stats.destructive}</div>
          <div class="stat-label">Destructive</div>
        </div>
      </div>
      
      <div class="stats-breakdown">
        <h3>Changes by Type</h3>
        <table class="breakdown-table">
          <thead>
            <tr>
              <th>Object Type</th>
              <th>Added</th>
              <th>Modified</th>
              <th>Removed</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            ${this.generateTypeBreakdown(result.changes)}
          </tbody>
        </table>
      </div>
    </section>

    <section class="changes">
      <h2>Detailed Changes</h2>
      ${result.changes.length === 0 
        ? '<p class="no-changes">No differences found between source and target.</p>'
        : result.changes.map((change, index) => this.generateChangeCard(change, index)).join('\n')}
    </section>

    <footer class="footer">
      <p>Generated by SSSC Schema Compare</p>
    </footer>
  </div>

  <script>
    ${this.getScripts()}
  </script>
</body>
</html>`;
  }

  private calculateStats(changes: SchemaChange[]): { total: number; safe: number; warning: number; destructive: number } {
    const stats = { total: 0, safe: 0, warning: 0, destructive: 0 };
    for (const change of changes) {
      stats.total++;
      stats[change.riskLevel]++;
    }
    return stats;
  }

  private generateTypeBreakdown(changes: SchemaChange[]): string {
    const breakdown = new Map<string, { added: number; modified: number; removed: number }>();
    
    for (const change of changes) {
      if (!breakdown.has(change.objectType)) {
        breakdown.set(change.objectType, { added: 0, modified: 0, removed: 0 });
      }
      const counts = breakdown.get(change.objectType)!;
      counts[change.changeType]++;
    }

    let html = '';
    for (const [type, counts] of breakdown) {
      const total = counts.added + counts.modified + counts.removed;
      html += `
        <tr>
          <td>${this.escapeHtml(type)}</td>
          <td class="count-added">${counts.added || '-'}</td>
          <td class="count-modified">${counts.modified || '-'}</td>
          <td class="count-removed">${counts.removed || '-'}</td>
          <td><strong>${total}</strong></td>
        </tr>`;
    }
    return html;
  }

  private generateChangeCard(change: SchemaChange, index: number): string {
    const riskClass = `risk-${change.riskLevel}`;
    const changeTypeClass = `change-${change.changeType}`;
    
    return `
    <div class="change-card ${riskClass}">
      <div class="change-header" onclick="toggleChange(${index})">
        <div class="change-info">
          <span class="object-name">${this.escapeHtml(change.objectName)}</span>
          <span class="badge badge-type">${this.escapeHtml(change.objectType)}</span>
          <span class="badge ${changeTypeClass}">${change.changeType}</span>
          <span class="badge ${riskClass}">${change.riskLevel}</span>
        </div>
        <span class="toggle-icon" id="toggle-${index}">+</span>
      </div>
      
      ${change.warningMessage ? `<div class="warning-message">${this.escapeHtml(change.warningMessage)}</div>` : ''}
      
      <div class="change-details" id="details-${index}" style="display: none;">
        ${this.generateDiffView(change)}
        
        <div class="script-section">
          <h4>Generated Script</h4>
          <pre class="script-code">${this.escapeHtml(change.script || '-- No script generated')}</pre>
        </div>
      </div>
    </div>`;
  }

  private generateDiffView(change: SchemaChange): string {
    if (!change.sourceDefinition && !change.targetDefinition) {
      return '';
    }

    if (change.changeType === 'added') {
      return `
        <div class="diff-section">
          <h4>New Definition</h4>
          <pre class="diff-code diff-added">${this.escapeHtml(change.sourceDefinition || '')}</pre>
        </div>`;
    }

    if (change.changeType === 'removed') {
      return `
        <div class="diff-section">
          <h4>Removed Definition</h4>
          <pre class="diff-code diff-removed">${this.escapeHtml(change.targetDefinition || '')}</pre>
        </div>`;
    }

    // Modified - show side-by-side or unified diff
    const diffHtml = this.generateUnifiedDiff(
      change.targetDefinition || '', 
      change.sourceDefinition || ''
    );

    return `
      <div class="diff-section">
        <h4>Changes (Target → Source)</h4>
        <div class="diff-view">${diffHtml}</div>
      </div>`;
  }

  private generateUnifiedDiff(oldText: string, newText: string): string {
    const diff = Diff.diffLines(oldText, newText);
    let html = '<pre class="diff-unified">';
    
    for (const part of diff) {
      const lines = part.value.split('\n').filter(line => line !== '' || part.value === '\n');
      for (const line of lines) {
        if (part.added) {
          html += `<span class="diff-line diff-line-added">+ ${this.escapeHtml(line)}</span>\n`;
        } else if (part.removed) {
          html += `<span class="diff-line diff-line-removed">- ${this.escapeHtml(line)}</span>\n`;
        } else {
          html += `<span class="diff-line">  ${this.escapeHtml(line)}</span>\n`;
        }
      }
    }
    
    html += '</pre>';
    return html;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private getStyles(): string {
    return `
      * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
      }
      
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f5f5f5;
      }
      
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
      }
      
      .header {
        background: linear-gradient(135deg, #1976d2, #1565c0);
        color: white;
        padding: 30px;
        border-radius: 8px;
        margin-bottom: 20px;
      }
      
      .header h1 {
        margin-bottom: 15px;
      }
      
      .report-meta p {
        margin: 5px 0;
        opacity: 0.9;
      }
      
      .summary, .changes {
        background: white;
        padding: 25px;
        border-radius: 8px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      }
      
      h2 {
        color: #1976d2;
        margin-bottom: 20px;
        padding-bottom: 10px;
        border-bottom: 2px solid #e0e0e0;
      }
      
      .stats-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 15px;
        margin-bottom: 25px;
      }
      
      .stat-card {
        padding: 20px;
        border-radius: 8px;
        text-align: center;
        color: white;
      }
      
      .stat-total { background: #607d8b; }
      .stat-safe { background: #4caf50; }
      .stat-warning { background: #ff9800; }
      .stat-destructive { background: #f44336; }
      
      .stat-number {
        font-size: 2.5em;
        font-weight: bold;
      }
      
      .stat-label {
        font-size: 0.9em;
        opacity: 0.9;
      }
      
      .breakdown-table {
        width: 100%;
        border-collapse: collapse;
      }
      
      .breakdown-table th,
      .breakdown-table td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #e0e0e0;
      }
      
      .breakdown-table th {
        background: #f5f5f5;
        font-weight: 600;
      }
      
      .count-added { color: #4caf50; }
      .count-modified { color: #ff9800; }
      .count-removed { color: #f44336; }
      
      .change-card {
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        margin-bottom: 15px;
        overflow: hidden;
      }
      
      .change-card.risk-safe { border-left: 4px solid #4caf50; }
      .change-card.risk-warning { border-left: 4px solid #ff9800; }
      .change-card.risk-destructive { border-left: 4px solid #f44336; }
      
      .change-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px;
        background: #fafafa;
        cursor: pointer;
      }
      
      .change-header:hover {
        background: #f0f0f0;
      }
      
      .change-info {
        display: flex;
        align-items: center;
        gap: 10px;
        flex-wrap: wrap;
      }
      
      .object-name {
        font-weight: 600;
        font-family: 'Consolas', 'Monaco', monospace;
      }
      
      .badge {
        padding: 4px 8px;
        border-radius: 4px;
        font-size: 0.75em;
        font-weight: 500;
        text-transform: uppercase;
      }
      
      .badge-type { background: #e0e0e0; color: #333; }
      .change-added { background: #c8e6c9; color: #2e7d32; }
      .change-modified { background: #fff3e0; color: #e65100; }
      .change-removed { background: #ffcdd2; color: #c62828; }
      .risk-safe { background: #c8e6c9; color: #2e7d32; }
      .risk-warning { background: #fff3e0; color: #e65100; }
      .risk-destructive { background: #ffcdd2; color: #c62828; }
      
      .toggle-icon {
        font-size: 1.5em;
        font-weight: bold;
        color: #666;
      }
      
      .warning-message {
        padding: 10px 15px;
        background: #fff3e0;
        color: #e65100;
        font-size: 0.9em;
      }
      
      .change-details {
        padding: 20px;
        border-top: 1px solid #e0e0e0;
      }
      
      .diff-section, .script-section {
        margin-bottom: 20px;
      }
      
      .diff-section h4, .script-section h4 {
        margin-bottom: 10px;
        color: #666;
      }
      
      .diff-code, .script-code, .diff-unified {
        background: #263238;
        color: #aed581;
        padding: 15px;
        border-radius: 4px;
        overflow-x: auto;
        font-family: 'Consolas', 'Monaco', monospace;
        font-size: 0.85em;
        white-space: pre-wrap;
        word-wrap: break-word;
      }
      
      .diff-added { border-left: 4px solid #4caf50; }
      .diff-removed { border-left: 4px solid #f44336; }
      
      .diff-line { display: block; }
      .diff-line-added { color: #81c784; background: rgba(76, 175, 80, 0.1); }
      .diff-line-removed { color: #e57373; background: rgba(244, 67, 54, 0.1); }
      
      .no-changes {
        text-align: center;
        color: #666;
        padding: 40px;
        font-style: italic;
      }
      
      .footer {
        text-align: center;
        padding: 20px;
        color: #666;
        font-size: 0.9em;
      }
      
      @media print {
        .toggle-icon { display: none; }
        .change-details { display: block !important; }
        .change-header { cursor: default; }
      }
    `;
  }

  private getScripts(): string {
    return `
      function toggleChange(index) {
        const details = document.getElementById('details-' + index);
        const toggle = document.getElementById('toggle-' + index);
        
        if (details.style.display === 'none') {
          details.style.display = 'block';
          toggle.textContent = '-';
        } else {
          details.style.display = 'none';
          toggle.textContent = '+';
        }
      }
      
      // Expand all for printing
      window.onbeforeprint = function() {
        document.querySelectorAll('.change-details').forEach(el => {
          el.style.display = 'block';
        });
      };
    `;
  }
}

export default ReportGeneratorService;
